services:
  backend:
    build: .
    container_name: backend
    command: sh -c "python manage.py migrate && python scripts/ensure_superuser.py && python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: hotel_room_booking
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotelpass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: hotel_room_booking
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotelpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel -d hotel_room_booking"]
      interval: 3s
      timeout: 5s
      retries: 20
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: